DROP TABLE IF EXISTS TASK_SCHEDULE;
DROP TABLE IF EXISTS TASK_STATUS;
DROP TABLE IF EXISTS TASK_HISTORY;

CREATE TABLE TASK_SCHEDULE(
	TASK_ID VARCHAR(100) PRIMARY KEY NOT NULL,
	TASK_NAME VARCHAR(500) DEFAULT NULL,
	TASK_DURATION INTEGER NOT NULL,
	TASK_CRON_SCHEDULE VARCHAR(100) DEFAULT NULL,
	TASK_TYPE VARCHAR(1) NOT NULL,
	TASK_STATUS VARCHAR(50) NOT NULL,
	TASK_PRIORITY VARCHAR(50) NOT NULL
);

CREATE TABLE TASK_STATUS(
	TASK_ID VARCHAR(100) PRIMARY KEY,
	TASK_NAME VARCHAR(500) DEFAULT NULL,
	TASK_DURATION INTEGER NOT NULL,
	TASK_TYPE VARCHAR(1) NOT NULL,
	TASK_STATUS VARCHAR(50) NOT NULL,
	TASK_PRIORITY VARCHAR(50) NOT NULL,
	TASK_ARRIVAL_TIME TIMESTAMP NOT NULL,
	TASK_START_TIME TIMESTAMP,
	TASK_END_TIME TIMESTAMP,
	TASK_NUMBER_OF_PREEMPTIONS INTEGER DEFAULT 0,
	FOREIGN KEY (TASK_ID) REFERENCES TASK_SCHEDULE(TASK_ID) ON DELETE CASCADE
);

CREATE TABLE TASK_HISTORY(
	TASK_ID VARCHAR(500),
	TASK_NAME VARCHAR(500) DEFAULT NULL,
	TASK_DURATION INTEGER NOT NULL,
	TASK_TYPE VARCHAR(1) NOT NULL,
	TASK_STATUS VARCHAR(50) NOT NULL,
	TASK_PRIORITY VARCHAR(50) NOT NULL,
	TASK_ARRIVAL_TIME TIMESTAMP NOT NULL,
	TASK_START_TIME TIMESTAMP,
	TASK_END_TIME TIMESTAMP,
	IS_TASK_RUN_COMPLETED BOOLEAN DEFAULT FALSE
);
	